# Generated by sila2.code_generator; sila2.__version__: 0.12.2
from __future__ import annotations

from datetime import timedelta
from typing import TYPE_CHECKING, List

from sila2.server import MetadataDict, ObservableCommandInstance

from ..generated.spectrumacquisitionservice import (
    ConfigureScanAndRunBackground_Responses,
    RunScan_Responses,
    ScanConfiguration,
    SpectrumAcquisitionServiceBase,
    Wavenumber,
)

if TYPE_CHECKING:
    from ..server import Server


class SpectrumAcquisitionServiceImpl(SpectrumAcquisitionServiceBase):
    def __init__(self, parent_server: Server) -> None:
        super().__init__(parent_server=parent_server)

        # Default lifetime of observable command instances. Possible values:
        # None: Command instance is valid and stored in memory until server shutdown
        # datetime.timedelta: Command instance is deleted after this duration, can be increased during command runtime
        self.ConfigureScanAndRunBackground_default_lifetime_of_execution = timedelta(minutes=30)
        self.RunScan_default_lifetime_of_execution = timedelta(minutes=30)

    def get_MaximumSupportedWavenumber(self, *, metadata: MetadataDict) -> Wavenumber:
        raise NotImplementedError  # TODO

    def get_MinimumSupportedWavenumber(self, *, metadata: MetadataDict) -> Wavenumber:
        raise NotImplementedError  # TODO

    def get_SupportedResolutions(self, *, metadata: MetadataDict) -> List[Wavenumber]:
        raise NotImplementedError  # TODO

    def ConfigureScanAndRunBackground(
        self, ScanConfiguration: ScanConfiguration, *, metadata: MetadataDict, instance: ObservableCommandInstance
    ) -> ConfigureScanAndRunBackground_Responses:
        # set execution status from `waiting` to `running`
        instance.begin_execution()

        raise NotImplementedError  # TODO

    def RunScan(self, *, metadata: MetadataDict, instance: ObservableCommandInstance) -> RunScan_Responses:
        # set execution status from `waiting` to `running`
        instance.begin_execution()

        raise NotImplementedError  # TODO
