# Generated by sila2.code_generator; sila2.__version__: 0.12.2
from dataclasses import dataclass, field
from datetime import datetime, timedelta
from typing import Any, List, Optional, Union
import logging

from sila2.features.lockcontroller import (
    InvalidLockIdentifier,
    LockControllerBase,
    LockControllerFeature,
    LockServer_Responses,
    ServerAlreadyLocked,
    ServerNotLocked,
    UnlockServer_Responses,
)

from sila2.framework import Command, Feature, FullyQualifiedIdentifier, Property
from sila2.server import MetadataInterceptor, SilaServer
from sila2.server.metadata_dict import MetadataDict

from .spectrumacquisitionservice_impl import (
    unlocked_commands as spectrum_unlocked_commands
)

unlocked_commands: List[Union[FullyQualifiedIdentifier, Command, Property]] = [
    LockControllerFeature["LockServer"],
    LockControllerFeature["UnlockServer"],
    LockControllerFeature["IsLocked"],
]
unlocked_commands.extend(spectrum_unlocked_commands)

logger = logging.getLogger(__name__)

@dataclass
class Lock:
    token: str
    timeout_duration: timedelta
    last_usage: datetime = field(default_factory=lambda: datetime.now())

    @property
    def is_expired(self):
        if self.timeout_duration == timedelta(seconds=0):
            return False
        return (datetime.now() - self.timeout_duration) > self.last_usage


class LockControllerImpl(LockControllerBase):
    def __init__(self, parent_server: SilaServer):
        super().__init__(parent_server=parent_server)
        self.lock: Optional[Lock] = None
        self.parent_server.add_metadata_interceptor(LockControllerInterceptor(self))

    @property
    def is_locked(self) -> bool:
        if self.lock is None:
            return False

        if self.lock.is_expired:
            self.lock = None

        return self.lock is not None

    def get_IsLocked(self, *, metadata: MetadataDict) -> bool:
        return self.is_locked

    def LockServer(self, LockIdentifier: str, Timeout: int, *, metadata: MetadataDict) -> LockServer_Responses:
        if self.is_locked:
            raise ServerAlreadyLocked

        self.lock = Lock(LockIdentifier, timedelta(seconds=Timeout))
        return LockServer_Responses()

    def UnlockServer(self, LockIdentifier: str, *, metadata: MetadataDict) -> UnlockServer_Responses:
        if not self.is_locked:
            raise ServerNotLocked

        if self.lock.token != LockIdentifier:
            raise InvalidLockIdentifier

        self.lock = None
        return UnlockServer_Responses()

    def get_calls_affected_by_LockIdentifier(self) -> List[Union[Feature, Command, Property, FullyQualifiedIdentifier]]:
        # Create a set of unlocked FQIs for efficient lookup
        unlocked_set = {
            item.fully_qualified_identifier if hasattr(item, "fully_qualified_identifier") else item
            for item in unlocked_commands
        }

        affected_calls = []
        for feature in self.parent_server.features.values():
            # The core SiLAService feature should never be locked
            if feature._identifier == "SiLAService":
                continue

            # Combine all commands and properties from the feature into one list
            all_callables = (
                list(feature._observable_commands.values())
                + list(feature._unobservable_commands.values())
                + list(feature._observable_properties.values())
                + list(feature._unobservable_properties.values())
            )

            # Add any callable to the affected list if it's not in the unlocked set
            for call in all_callables:
                if call.fully_qualified_identifier not in unlocked_set:
                    affected_calls.append(call)
            
            logger.debug("Affected calls: %s", affected_calls)
        return affected_calls

class LockControllerInterceptor(MetadataInterceptor):
    def __init__(self, lockcontroller_impl: LockControllerImpl):
        super().__init__([LockControllerFeature["LockIdentifier"]])
        self.lockcontroller_impl = lockcontroller_impl

    def intercept(self, parameters: Any, metadata: MetadataDict, target_call: FullyQualifiedIdentifier) -> None:
        if not self.lockcontroller_impl.is_locked:
            return
        
        token: str = metadata[LockControllerFeature["LockIdentifier"]]
        logger.debug("Intercepting locked call %s with LockIdentifier: %s", target_call, token)

        if token != self.lockcontroller_impl.lock.token:
            raise InvalidLockIdentifier("The provided LockIdentifier is not valid.")
        
