# Generated by sila2.code_generator; sila2.__version__: 0.12.2
from __future__ import annotations

from datetime import timedelta
from typing import TYPE_CHECKING, List
import logging
from threading import Lock
import collections
import csv

from sila2.server import MetadataDict, ObservableCommandInstance
from sila2.framework import CommandExecutionNotAccepted

from ..generated.spectrumacquisitionservice import (
    ConfigureScanAndRunBackground_Responses,
    RunScan_Responses,
    ScanConfiguration,
    SpectrumAcquisitionServiceFeature,
    SpectrumAcquisitionServiceBase,
    Wavenumber,
    ConfigurationNotSet,
    InvalidConfiguration,
)
from sila2.framework import FullyQualifiedIdentifier

from .ftir_pywinauto import start_and_login, configure_scan, run_background_scan, run_scan

if TYPE_CHECKING:
    from ..server import Server

unlocked_commands: List[FullyQualifiedIdentifier] = [
    SpectrumAcquisitionServiceFeature["SupportedResolutions"],
    SpectrumAcquisitionServiceFeature["MinimumSupportedWavenumber"],
    SpectrumAcquisitionServiceFeature["MaximumSupportedWavenumber"],
    SpectrumAcquisitionServiceFeature["CurrentScanConfiguration"],
]

logger = logging.getLogger(__name__)

class SpectrumAcquisitionServiceImpl(SpectrumAcquisitionServiceBase):
    def __init__(self, parent_server: Server) -> None:
        super().__init__(parent_server=parent_server)

        # Default lifetime of observable command instances. Possible values:
        # None: Command instance is valid and stored in memory until server shutdown
        # datetime.timedelta: Command instance is deleted after this duration, can be increased during command runtime
        self.ConfigureScanAndRunBackground_default_lifetime_of_execution = timedelta(minutes=30)
        self.RunScan_default_lifetime_of_execution = timedelta(minutes=30)
        self.execution_lock = Lock()
        start_and_login() # Start the FTIR application and log in
        
    def get_MaximumSupportedWavenumber(self, *, metadata: MetadataDict) -> Wavenumber:
        return 4000.0

    def get_MinimumSupportedWavenumber(self, *, metadata: MetadataDict) -> Wavenumber:
        return 650.0

    def get_SupportedResolutions(self, *, metadata: MetadataDict) -> List[Wavenumber]:
        return [2.0, 4.0, 8.0, 16.0]

    def ConfigureScanAndRunBackground(
        self, ScanConfiguration: ScanConfiguration, *, 
        metadata: MetadataDict, instance: ObservableCommandInstance
        ) -> ConfigureScanAndRunBackground_Responses:
        
        if not self.execution_lock.acquire(blocking=False):
            raise CommandExecutionNotAccepted("Another command is currently running, please try again later.")
        
        try:
            instance.begin_execution()
            # Check arguments
            if (not ScanConfiguration.SampleScans >= 1
                or not ScanConfiguration.Resolution in self.get_SupportedResolutions()
                or not ScanConfiguration.LowerWavenumber >= self.get_MinimumSupportedWavenumber()
                or not ScanConfiguration.UpperWavenumber <= self.get_MaximumSupportedWavenumber()):
                raise InvalidConfiguration()

            # Set config in backend and application
            self.update_CurrentScanConfiguration(ScanConfiguration)
            instance.progress = 0.1
            configure_scan(ScanConfiguration)
            instance.progress = 0.5
            
            # Run background scan
            run_background_scan(ScanConfiguration)
            instance.progress = 1.0
            
            return ConfigureScanAndRunBackground_Responses()

        except TypeError as e:
            raise InvalidConfiguration(f"Invalid configuration: {e}")

        finally:
            self.execution_lock.release()

    def RunScan(self, *, metadata: MetadataDict, instance: ObservableCommandInstance) -> RunScan_Responses:
        
        if not self.execution_lock.acquire(blocking=False):
            raise CommandExecutionNotAccepted("Another command is currently running, please try again later.")
        try:
            if self.current_CurrentScanConfiguration == None:
                raise ConfigurationNotSet()
            
            # set execution status from `waiting` to `running`
            instance.begin_execution() 
            
            instance.progress = 0.1
            spectrum_data_path = run_scan(self.current_CurrentScanConfiguration)
            instance.progress = 0.5
            
            # Retrieve the spectrum data
            # Retrieve the spectrum data
            SpectrumPoint = collections.namedtuple("SpectrumPoint", ["Wavenumber", "Absorbance"])
            spectrum_data = []
            with open(spectrum_data_path, 'r', newline='') as csvfile:
                reader = csv.reader(csvfile)
                next(reader)  # Skip header row
                for row in reader:
                    if row: # ensure row is not empty
                        wavenumber = float(row[0])
                        absorbance = float(row[1])
                        spectrum_data.append(SpectrumPoint(Wavenumber=wavenumber, Absorbance=absorbance))
            
            instance.progress = 1.0
            return RunScan_Responses(SampleSpectrum=spectrum_data)
        
        finally:
            self.execution_lock.release()
