# Generated by sila2.code_generator; sila2.__version__: 0.12.2

from typing import Optional
from uuid import UUID, uuid4

from sila2.server import SilaServer

from .feature_implementations.lockcontroller_impl import LockControllerImpl
from .feature_implementations.spectrumacquisitionservice_impl import SpectrumAcquisitionServiceImpl
from .generated.lockcontroller import LockControllerFeature
from .generated.spectrumacquisitionservice import SpectrumAcquisitionServiceFeature


class Server(SilaServer):
    def __init__(
        self,
        server_uuid: Optional[UUID] = None,
        name: Optional[str] = None,
        description: Optional[str] = None,
    ):
        if name is None:
            name = "Agilent Cary 630 FTIR"
        if description is None:
            description = "SiLA2 server for Agilent Cary 630 FTIR spectrometer. It can be used to take FTIR spectra and control the instrument."
        super().__init__(
            server_name=name,
            server_description=description,
            server_type="AgilentCary630FTIR",
            server_version="0.1",
            server_vendor_url="https://gitlab.com/TODO:",
            server_uuid=server_uuid if server_uuid is not None else uuid4(),
        )

        self.spectrumacquisitionservice = SpectrumAcquisitionServiceImpl(self)
        self.set_feature_implementation(SpectrumAcquisitionServiceFeature, self.spectrumacquisitionservice)

        self.set_feature_implementation(LockControllerFeature, LockControllerImpl(self))
