[project]
name = "ftir_sila_package"
version = "0.0.0"
requires-python = ">=3.8"
dependencies = [
    "sila2",
    "typer",
]

[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["ftir_sila_package*"]

[tool.setuptools.package-data]
"ftir_sila_package.generated" = [
    "*/*.sila.xml",
    "*/*.proto",
]
