#ifndef MG400_ALARM_SERVO_HPP
#define MG400_ALARM_SERVO_HPP

#include "mg400_ros2_bringup/alarms/mg400_error_types.hpp"
#include <array>

namespace alarms::servo {

// Data from alarm_servo.json.
constexpr std::array<ErrorInfo, 81> data = {{
    {0, 0, {"No error", "", ""}},
    {1, 0, {"Communication error", "", ""}},
    {2, 0, {"Axis error", "", ""}},
    {3, 0, {"Fieldbus has lost synchronism", "", ""}},
    {10, 5, {"Position outside of permissible range of SWLimit", "", ""}},
    {11, 5, {"Hardware end switch is active", "", ""}},
    {12, 5, {"This error occurs if a linear axis has more than 2^15 32-bit overflows of the position in increments", "", ""}},
    {13, 0, {"Drive status Halt or Quickstop is not supported", "", ""}},
    {14, 0, {"Drive has no power", "", ""}},
    {15, 0, {"This error is no longer used", "", ""}},
    {16, 0, {"Position lag error. Difference between set and current position exceeds the given limit", "", ""}},
    {17, 0, {"Homing error reported by axis", "", ""}},
    {18, 0, {"A problem with the license occurred", "", ""}},
    {20, 0, {"Controller enable not done or brake applied", "", ""}},
    {21, 0, {"Axis in wrong controller mode", "", ""}},
    {25, 0, {"Invalid action at logical axis", "", ""}},
    {30, 0, {"Motion creating module has not been called again before end of the motion", "", ""}},
    {31, 0, {"Type of given AXIS_REF variable is not AXIS_REF", "", ""}},
    {32, 0, {"AXIS_REF variable has been exchanged while the module was active", "", ""}},
    {33, 0, {"Axis disabled while being moved. MC_Power.bRegulatorOn", "", ""}},
    {34, 0, {"Axis in its current state cannot execute a motion command, because the axis doesn’t signal currently that it follows the target values", "", ""}},
    {35, 0, {"The drive reported an error during an ongoing movement.", "", ""}},
    {40, 0, {"Maximum velocity fMaxVelocity exceeded", "", ""}},
    {41, 0, {"Maximum acceleration fMaxAcceleration exceeded", "", ""}},
    {42, 0, {"Maximum deceleration fMaxDeceleration exceeded", "", ""}},
    {50, 0, {"Invalid velocity or acceleration values", "", ""}},
    {51, 0, {"Mode requests for safety reasons use of end switches", "", ""}},
    {60, 0, {"No free handle has been sent to open file", "", ""}},
    {70, 0, {"Mode not supported", "", ""}},
    {71, 0, {"In current mode, controller mode cannot be changed", "", ""}},
    {72, 0, {"SMC_SetControllerMode has been interrupted by MC_Stop or errorstop", "", ""}},
    {75, 0, {"Axis not in correct controller mode. Deprecated, no longer returned by SMC_SetTorque", "", ""}},
    {80, 0, {"Error at startup of the axis group", "", ""}},
    {81, 0, {"The axis is not yet in the required state", "", ""}},
    {85, 0, {"The function block does not support virtual or logical axes", "", ""}},
    {86, 0, {"The number of absolute bits is invalid, must be in the range 8 - 32", "", ""}},
    {90, 0, {"Invalid values", "", ""}},
    {91, 0, {"Gearing parameters must not be changed as long as the drive is under control", "", ""}},
    {92, 0, {"Invalid modulo period (<= 0 or greater than half the bus bandwidth)", "", ""}},
    {93, 0, {"The modulo period in increments is not an integer, but the modulo-handling is done by the drive", "", ""}},
    {110, 0, {"Axis contain no information on cycle time (fTaskCycle = 0).", "", ""}},
    {120, 0, {"Axis without error", "", ""}},
    {121, 0, {"Axis does not perform error-reset", "", ""}},
    {122, 0, {"Error could not be reset", "", ""}},
    {123, 0, {"Communication with the axis did not work", "", ""}},
    {170, 0, {"Axis has not been in standstill state", "", ""}},
    {171, 0, {"Error at start of homing action.", "", ""}},
    {172, 0, {"Error at start of homing action.", "", ""}},
    {173, 0, {"Error at stop after homing. Deceleration may not be set.", "", ""}},
    {174, 0, {"Drive is in errorstop status. Homing cannot be executed.", "", ""}},
    {1000, 0, {"Target is not licensed for CNC.", "", ""}},
    {5000, 0, {"Nominator of the conversion factor dwRatioTechUnitsDenom of the Encoder reference is 0", "", ""}},
    {60929, 0, {"Communication error. ", "", ""}},
    {8752, 0, {"IPM abnormal protection ", "", ""}},
    {8992, 0, {"Software overcurrent protection", "", ""}},
    {9088, 0, {"Zero point current bias too large protection", "", ""}},
    {30080, 0, {"EtherCAT communication abnormal protection", "", ""}},
    {33920, 0, {"Exceeding max speed protection", "", ""}},
    {33921, 0, {"Speed error too large protection", "", ""}},
    {33922, 0, {"Motor lost speed protection", "", ""}},
    {29568, 0, {"Encoder communication abnormal protection", "", ""}},
    {29569, 0, {"Encoder malfunction", "", ""}},
    {29570, 0, {"Encoder battery abnormal protection", "", ""}},
    {34321, 0, {"Postion error too large protection", "", ""}},
    {34322, 0, {"Postion setting out of range", "", ""}},
    {12832, 0, {"Power between PN low protection", "", ""}},
    {12816, 0, {"Power between PN high protection", "", ""}},
    {17168, 0, {"Driver temperature high protection", "", ""}},
    {9040, 0, {"Module overload protection", "", ""}},
    {13184, 0, {"Driver output phase error protection", "", ""}},
    {13185, 0, {"Driver output phase lost protection", "", ""}},
    {12592, 0, {"Driver input phase lost protection", "", ""}},
    {21569, 0, {"Dirver connection abnormal protection", "", ""}},
    {21008, 0, {"Driver recognition abnormal protection", "", ""}},
    {21120, 0, {"Internal error 1", "", ""}},
    {21121, 0, {"Internal error 2", "", ""}},
    {21122, 0, {"STO safety wiring fault protection", "", ""}},
    {29056, 0, {"Motor overload protection", "", ""}},
    {16912, 0, {"Manufacturer testing 32", "", ""}},
    {29057, 0, {"Brake malfunction", "", ""}},
    {29058, 0, {"External brake resistors overload protection", "", ""}}
}};

} // namespace alarms::servo

#endif // MG400_ALARM_SERVO_HPP