#ifndef MG400_ALARM_CONTROLLER_HPP
#define MG400_ALARM_CONTROLLER_HPP

#include "mg400_ros2_bringup/alarms/mg400_error_types.hpp"
#include <array>

namespace alarms::controller {

// Data from alarm_controller.json
constexpr std::array<ErrorInfo, 183> data = {{
    {0, 0, {"No error", "", ""}},
    {16, 5, {"Inverse kinematics error with singularity", "", ""}},
    {17, 5, {"Inverse kinematics error with no solution", "", ""}},
    {18, 5, {"Inverse kinematics error with result out of working area", "", ""}},
    {19, 5, {"Duplicated data in JUMP or ARC or Circles instruction", "", ""}},
    {20, 5, {"Wrong input parameters for arc", "", ""}},
    {21, 5, {"Wrong JUMP parameters", "", ""}},
    {22, 5, {"Wrong arm orientation switch", "", ""}},
    {23, 5, {"Plan point during linear motion out of working area", "", ""}},
    {24, 5, {"Plan point during circular arc motion out of working area", "", ""}},
    {26, 5, {"Inverse kinematics error with elbow singularity", "", ""}},
    {27, 5, {"Inverse kinematics error with wrist singularity", "", ""}},
    {28, 5, {"Wrong mode for motion instruction", "", ""}},
    {29, 5, {"Wrong input parameters for speed", "", ""}},
    {32, 5, {"Inverse kinematics singularity during moving", "", ""}},
    {33, 5, {"Inverse kinematics with no solution during moving", "", ""}},
    {34, 5, {"Inverse kinematcis with result out of working area during moving", "", ""}},
    {35, 5, {"Inverse kinematics elbow singularity during moving", "", ""}},
    {36, 5, {"Inverse kinematics wrist singularity during moving", "", ""}},
    {37, 5, {"Joint target position change over 180 degree during moving", "", ""}},
    {48, 5, {"Joint1 overspeed", "", ""}},
    {49, 5, {"Joint2 overspeed", "", ""}},
    {50, 5, {"Joint3 overspeed", "", ""}},
    {51, 5, {"Joint4 overspeed", "", ""}},
    {52, 5, {"Joint5 overspeed", "", ""}},
    {53, 5, {"Joint6 overspeed", "", ""}},
    {54, 5, {"Joint1 position lag error", "", ""}},
    {55, 5, {"Joint2 position lag error", "", ""}},
    {56, 5, {"Joint3 position lag error", "", ""}},
    {57, 5, {"Joint4 position lag error", "", ""}},
    {58, 5, {"Joint5 position lag error", "", ""}},
    {59, 5, {"Joint6 position lag error", "", ""}},
    {64, 5, {"Joint1 exceeds positive limit", "", ""}},
    {65, 5, {"Joint1 exceeds negative limit", "", ""}},
    {66, 5, {"Joint2 exceeds positive limit", "", ""}},
    {67, 5, {"Joint2 exceeds negative limit", "", ""}},
    {68, 5, {"Joint3 exceeds positive limit", "", ""}},
    {69, 5, {"Joint3 exceeds negative limit", "", ""}},
    {70, 5, {"Joint4 exceeds positive limit", "", ""}},
    {71, 5, {"Joint4 exceeds negative limit", "", ""}},
    {72, 5, {"Joint5 exceeds positive limit", "", ""}},
    {73, 5, {"Joint5 exceeds negative limit", "", ""}},
    {74, 5, {"Joint6 exceeds positive limit", "", ""}},
    {75, 5, {"Joint6 exceeds negative limit", "", ""}},
    {80, 0, {"Joint1 lose step", "", ""}},
    {81, 0, {"Joint2 lose step", "", ""}},
    {82, 0, {"Joint3 lose step", "", ""}},
    {83, 0, {"Joint4 lose step", "", ""}},
    {84, 0, {"Joint5 lose step", "", ""}},
    {85, 0, {"Joint6 lose step", "", ""}},
    {96, 0, {"Joint1 Servo alarm", "", ""}},
    {97, 0, {"Joint1 Servo power off", "", ""}},
    {99, 0, {"Joint2 Servo alarm", "", ""}},
    {100, 0, {"Joint2 Servo power off", "", ""}},
    {102, 0, {"Joint3 Servo alarm", "", ""}},
    {103, 0, {"Joint3 Servo power off", "", ""}},
    {105, 0, {"Joint4 Servo alarm", "", ""}},
    {106, 0, {"Joint4 Servo power off", "", ""}},
    {108, 0, {"Joint5 Servo alarm", "", ""}},
    {109, 0, {"Joint5 Servo power off", "", ""}},
    {111, 0, {"Joint6 Servo alarm", "", ""}},
    {112, 0, {"Joint6 Servo power off", "", ""}},
    {114, 5, {"Robot homing failed", "", ""}},
    {115, 0, {"Robot Servo on failed", "", ""}},
    {116, 0, {"Emergency button pressed", "", ""}},
    {117, 5, {"Collision detection", "", ""}},
    {118, 0, {"Security IO lost", "", ""}},
    {119, 0, {"Electronic skin collision detection", "", ""}},
    {120, 5, {"Six dimensions are not enabled", "", ""}},
    {121, 5, {"ERR_INITIALFAILED", "", ""}},
    {122, 0, {"ERR_SWITCHOKERR", "", ""}},
    {123, 0, {"ERR_DISCHARGEOKERR", "", ""}},
    {124, 0, {"ERR_ACDETECTERR", "", ""}},
    {125, 0, {"ERR_ECATONLINEERR", "", ""}},
    {126, 0, {"ERR_CABINETPSWITCHERR", "", ""}},
    {128, 0, {"Internal error - time overflow", "", ""}},
    {131, 0, {"Terminal IO board offline", "", "Check whether the hardware is working properly, and restart the controller, or contact support engineer"}},
    {144, 5, {"ERR_PLAN1_CIRCLE_INPUT_PARAM", "", ""}},
    {146, 5, {"Inching parameter error", "", ""}},
    {161, 5, {"Error switching control mode", "", ""}},
    {1772, 0, {"ERR_SWITCHOKERR", "", ""}},
    {1773, 0, {"ERR_DISCHARGEOKERR", "", ""}},
    {1775, 0, {"ERR_ACDETECTERR", "", ""}},
    {1776, 0, {"ERR_ECATONLINEERR", "", ""}},
    {1777, 0, {"ERR_CABINETPSWITCHERR", "", ""}},
    {4096, 5, {"Faield to open mechanical file", "", ""}},
    {8192, 5, {"Faield to open project file", "", ""}},
    {8193, 5, {"Faield to open program file", "", ""}},
    {8194, 5, {"Faield to open global variable file", "", ""}},
    {8195, 5, {"Failed to open teaching point file", "", ""}},
    {8196, 0, {"Failed to start debugger process", "", ""}},
    {12288, 0, {"Emergency stop detected", "", ""}},
    {12289, 0, {"External emergency stop detected", "", ""}},
    {12290, 0, {"Axis1 not in Bus Mode", "", ""}},
    {12291, 0, {"Axis2 not in Bus Mode", "", ""}},
    {12292, 0, {"Axis3 not in Bus Mode", "", ""}},
    {12293, 0, {"Axis4 not in Bus Mode", "", ""}},
    {12294, 0, {"Axis5 not in Bus Mode", "", ""}},
    {12295, 0, {"Axis6 not in Bus Mode", "", ""}},
    {12296, 0, {"Ontology of electricity", "", ""}},
    {12297, 0, {"Protective stop pressed ", "", ""}},
    {16384, 5, {"Obstructions were detected in the area", "", ""}},
    {16385, 5, {"Detect abnormal power loss", "", ""}},
    {20480, 0, {"Energy board Modbus dropped", "", ""}},
    {20481, 0, {"Before power supply, the voltage is higher than 51V", "", ""}},
    {20482, 0, {"Before power supply, the voltage is lower than 45V", "", ""}},
    {20483, 0, {"Detection current limiting chip alarm", "", ""}},
    {20484, 0, {"After power supply, the voltage is higher than 55V", "", ""}},
    {20485, 0, {"After power supply, the voltage is lower than 41.4V", "", ""}},
    {20486, 0, {"Internal first stable voltage 2.5v is abnormal", "", ""}},
    {20487, 0, {"Internal second stable voltage 2.5v is abnormal", "", ""}},
    {20489, 0, {"Detect the feed current greater than 17A", "", ""}},
    {20490, 0, {"Super power protection of cement resistance", "", ""}},
    {20491, 0, {"The overpower protection busbar current of cement resistance is greater than 26A", "", ""}},
    {20493, 5, {"Feed board fan current short circuit", "", ""}},
    {20494, 5, {"Feed board fan current break", "", ""}},
    {24576, 0, {"Security IO board Modebus dropped", "", ""}},
    {24578, 0, {"The contactor did not close as required for continuous 1S", "", ""}},
    {24579, 0, {"When the control is electrified, the energy board 2S does not return an electrified signal", "", ""}},
    {24581, 0, {" AC Status detection error", "", ""}},
    {24582, 0, {" After 5 minutes of power on, the online data did not update for 1min", "", ""}},
    {24583, 0, {" The panel switch is pressed", "", ""}},
    {32768, 5, {"SpeedFactor instructions have no input parameters", "", ""}},
    {32769, 5, {"SpeedFactor instruction parameters out of range", "", ""}},
    {32770, 5, {"DO parameter error", "", ""}},
    {32771, 5, {"DI parameter error", "", ""}},
    {33024, 5, {"No input parameters for CP instruction", "", ""}},
    {33025, 5, {"Input parameters of CP instruction out of range", "", ""}},
    {33280, 5, {"No input parameters for Arch instruction", "", ""}},
    {33281, 5, {"Index parameter of Arch instruction out of range", "", ""}},
    {33282, 5, {"Index parameter of Arch instruction not configured yet", "", ""}},
    {33536, 5, {"No input parameters for LimZ instruction", "", ""}},
    {33537, 5, {"Input parameters of LimZ instruction out of range", "", ""}},
    {33792, 5, {"No input parameters for Speed instruction", "", ""}},
    {33793, 5, {"Ratio parameter of Speed instruction out of range [1, 100]", "", ""}},
    {34048, 5, {"No input parameters for Accel instruction", "", ""}},
    {34049, 5, {"Ratio parameter of Accel instruction out of range [1, 100]", "", ""}},
    {34304, 5, {"No input parameters for Jerk instruction", "", ""}},
    {34305, 5, {"Ratio parameter of Jerk instruction out of range [1, 100]", "", ""}},
    {34560, 5, {"No input parameters for SpeedS instruction", "", ""}},
    {34561, 5, {"Ratio parameter of SpeedS instruction out of range [1, 100]", "", ""}},
    {34816, 5, {"No input parameters for SpeedR instruction", "", ""}},
    {34817, 5, {"Ratio parameter of SpeedR instruction out of range [1, 100]", "", ""}},
    {35072, 5, {"No input parameters for AccelS instruction", "", ""}},
    {35073, 5, {"Ratio parameter of AccelS instruction out of range [1, 100]", "", ""}},
    {35328, 5, {"No input parameters for AccelR instruction", "", ""}},
    {35329, 5, {"Ratio parameter of AccelR instruction out of range [1, 100]", "", ""}},
    {35584, 5, {"No input parameters for JerkS instruction", "", ""}},
    {35585, 5, {"Ratio parameter of JerkS instruction out of range [1, 100]", "", ""}},
    {35840, 5, {"No input parameters for JerkR instruction", "", ""}},
    {35841, 5, {"Ratio parameter of JerkR instruction out of range [1, 100]", "", ""}},
    {36096, 5, {"No input parameters for Go instruction", "", ""}},
    {36097, 5, {"No motion point parameter for Go instruction", "", ""}},
    {36098, 5, {"Incorrect motion point for Go instruction", "", ""}},
    {36099, 5, {"Incorrect control parameter for Go instruction", "", ""}},
    {36100, 5, {"Incorrect control parameter for MoveJ instruction", "", ""}},
    {36102, 5, {"The MoveJ instruction lacks coordinate point parameters", "", ""}},
    {36103, 5, {"Incorrect parameter for RP instruction", "", ""}},
    {36105, 5, {"Incorrect parameter for RJ instruction", "", ""}},
    {36109, 5, {"MoveJR instruction has no input parameters", "", ""}},
    {36352, 5, {"No input parameters for Move instruction", "", ""}},
    {36353, 5, {"No motion point parameter for Move instruction", "", ""}},
    {36354, 5, {"Incorrect motion point for Move instruction", "", ""}},
    {36355, 5, {"Incorrect control parameter for Move instruction", "", ""}},
    {36608, 5, {"No input parameters for Arch3 instruction", "", ""}},
    {36609, 5, {"No motion point parameter for Arch3 instruction", "", ""}},
    {36610, 5, {"Incorrect motion point for Arch3 instruction", "", ""}},
    {36611, 5, {"Incorrect control parameter for Arch3 instruction", "", ""}},
    {36864, 5, {"No input parameters for Jump instruction", "", ""}},
    {36865, 5, {"No motion point parameter for Jump instruction", "", ""}},
    {36866, 5, {"Incorrect motion point for Jump instruction", "", ""}},
    {36867, 5, {"Incorrect control parameter for Jump instruction", "", ""}},
    {40960, 5, {"The Circle3 directive has no input parameters", "", ""}},
    {40961, 5, {"The Circle3 directive lacks a coordinate point parameter", "", ""}},
    {40962, 5, {"Circle3 instruction coordinate point parameter error", "", ""}},
    {40963, 5, {"Error in Circle3 instruction control parameter", "", ""}},
    {41216, 5, {"The Spiral command has no input parameters", "", ""}},
    {41217, 5, {"The Spiral command lacks a coordinate point parameter", "", ""}},
    {41218, 5, {"Wrong Spiral command coordinate point parameter", "", ""}},
    {42240, 5, {"6 d force return to zero parameter error", "", ""}},
    {42241, 5, {"Six dimensions are not turned on", "", ""}},
    {45072, 5, {"Go instruction parameter error", "", ""}},
    {45080, 5, {"Check TOOL Param Error Option", "", ""}}
}};

} // namespace alarms::controller

#endif // MG400_ALARM_CONTROLLER_HPP